---
title: "R Notebook"
output: html_notebook
---

```{r}
#Load packages
#packages <- c("readxl")
#install.packages(setdiff(packages, rownames(installed.packages()))) 

#library(readxl)
```

```{r}
#Select folder that contains your BF_Cellpose_v2 output:
file_path <- rstudioapi::selectDirectory()
file_path
#file_path <- "/Users/paterna/Desktop/CellProfiler Analyst Results/IHM 3_1 BF"

```


```{r}
#Get file names for all files in the folder indicated by "path" that are the file type indicated by "pattern".
filenames <- list.files(path=file_path, pattern = "*.csv", full.names=TRUE)
#Load all files as data frames in the list of data frames "ldf".
ldf <- lapply(filenames, read.csv)
#Create function to convert area to equivalent diameter of a circle with the same area.
equivalent_diameter <- function(a){
  temp <- 2*sqrt(a/pi)
}

#equivalent_diameter_by_perimeter <- function(a){temp <- a/pi}

#Get equivalent diameter.
res <- lapply(ldf,equivalent_diameter)
#per <- lapply(ldf,equivalent_diameter_by_perimeter)

#Remove file path and type from file name.
file_values <- filenames
file_values <- gsub("*.csv", "",  file_values)
file_values <- gsub(paste0(file_path,"/*"),"",file_values)
experiment_name <- gsub( "scan_Plate_R_.*","", file_values[1])


#get well
well <- regmatches(file_values, regexpr("[^p][0-9][0-9]f", file_values))
well <- gsub("f","", well)

#Reformat data list to include equivalent diameter.
dl <- ldf
for (i in 1:length(ldf)){
temp <- ldf[[i]]
mdf <- res[[i]]
#pdf <- per[[i]]
#"Perim." for mac, but "Perimeter" for windows. I haven't added an if clause yet to catch that difference.
#temp <- cbind(file_values[i],well[i],temp[2:3], mdf["Area"],pdf["Perim."])
temp <- cbind(file_values[i],well[i],temp[2:3], mdf["Area"])
colnames(temp) <- c("filename","well","Area_microns","Perimeter_microns","Equivalent_Diameter_microns")    
dl[[i]] <- temp
}

```


```{r}
#Replace each file with a new one that includes equivalent diameter if desired.
#for (i in 1:length(dl)){write.csv(dl[[i]], file=filenames[i])}
```

```{r}
#Save all raw data values in a single file.
#Create empty data frame.
df <- as.data.frame(cbind(0,0,0,0,0))
#Set column names.
colnames(df) <- c("filename","well","Area_microns","Perimeter_microns","Equivalent_Diameter_microns")
#Loop through each data frame in the list of data frames and add them to the end of the empty data frame.
for (i in 1:length(dl)){
df <- rbind(df,dl[[i]])  
}
#Remove empty first row of the data frame.
df <- df[2:length(df[,1]),]

#Convert from pixels to microns (2.2 pixels/microns for 10x images)
#Set conversion factor
conversion <- 2.2
df[,4:5] <- round(df[,4:5]/conversion, digits = 2)
df[,3] <- round(df[,3]/conversion/conversion, digits =2 )

#Should we try to get rid of noncircular objects?
#ratio <- df$Equivalent_Diameter/df$Equivalent_Diameter_by_Perimeter
#df["ratio"] <- ratio
#df <- df[df$ratio >.85,]
#df <- df[df$ratio <=1,]
#plot(df$ratio)
#write.csv(df, file=paste0("filtered_",raw_file_name))

#Save data frame with raw values from each file.
write.csv(df, file=paste0(experiment_name,"_per_cell_data.csv"))

```


```{r}
#Save per image values in a single file.
#Create empty data frame.
df <- as.data.frame(cbind(0,0,0,0,0,0))
#Set column names.
colnames(df) <- c("filename","well","mean_Area_microns","mean_Perimeter_microns","mean_Equivalent_Diameter_microns","Cell_Count")
#Loop through each image calculating per image means and adding them to the data frame.
for (i in 1:length(dl)){
temp <- dl[[i]]
#Pixel to micron conversion is built in and will need to be changed if desired
sdf <-cbind(temp[1,1],temp[1,2],sum(temp[,3]/conversion/conversion)/length(temp[,3]),sum(temp[,4]/conversion)/length(temp[,4]),sum(temp[,5]/conversion)/length(temp[,5]),length(temp[,3]))
colnames(sdf) <- c("filename","well","mean_Area_microns","mean_Perimeter_microns","mean_Equivalent_Diameter_microns","Cell_Count")
df <- rbind(df,sdf)  
}

#Check for images that do not have any cells. Add them to the per image data frame with 0 values.
#Get list of images.
imagepath <- list.files(path=file_path, pattern = "*.jpg", full.names=TRUE)
#Remove path and file type from image name.
imagenames <- as.data.frame(t(as.data.frame(strsplit(imagepath, "/"))))
imagenames <- imagenames[,length(imagenames)]
imagenames <- gsub("*.jpg", "",  imagenames)
#Check if there are missing images.
if(length(imagenames) != length(filenames)){
#Identify missing images by well and location.
image_split <- as.data.frame(t(as.data.frame(strsplit(imagenames, "_"))))
file_split <- as.data.frame(t(as.data.frame(strsplit(filenames, "_"))))
u.images <- image_split[length(image_split)-1]
u.files <- file_split[length(file_split)-1]
#Create vector of missing image names.
missing <- imagenames[!u.images[,1] %in% u.files[,1]]
#Loop through each missing image. Add to per image data frame with 0 values.
for (i in 1:length(missing)){
  temp <- as.data.frame(cbind(missing[i],0,0,0,0,0))
  colnames(temp) <- colnames(df)
  df <- rbind(df, temp)
  }
}
#Remove empty first row.
df <- df[2:length(df[,1]), ]
#Save data frame.
write.csv(df, file=paste0(experiment_name,"_per_image_data.csv"))

```


